### PR TITLE
Renamed the classes

### PR DESCRIPTION
**Pull request by WebGertsog**
Renamed the classes of the "main-bg-wrapper" component according to the BEM methodology

### CODE REVIEW

**Review by Zolotarova-Nataliia — APPROVED** [review]
Approve all changes

**Comment by Androborn** [comment]
Needs correction.
Must be:     class="
      main-bg-wrapper__bg-shape
      main-bg-wrapper__bg-shape--X
    "

**Review by Androborn — APPROVED** [review]
Accepted

**Comment by Androborn** [comment]
Roman, please leave comments after fixes, other vice it's hard for me to spot them.

**Pull request merged**
